004
scyannickweber/einarbeitung pull request #4
Opened 2024-08-21 07:11 UTC by scyannickweber

2024-08-22 06:52 UTC, scibrahimelmas commented on 04_Datenbanken/databasecreate.py
> +            VALUES ("{e1}", "{e2}", "{e3}", "{e4}", "{e5}", "{e6}");"""
Wäre anfällig für eine SQL inection

2024-08-22 06:52 UTC, scibrahimelmas commented on 04_Datenbanken/databasecreate.py
> +            VALUES ("{e1}", "{e2}", "{e3}");"""
Wäre ebenfalls anfällig für eine SQL inection

2024-08-22 06:53 UTC, scibrahimelmas commented on 04_Datenbanken/databasecreate.py
> +            WHERE squadID = {squad_del_id} """
Wäre ebenfalls anfällig für eine SQL inection

2024-08-22 06:53 UTC, scibrahimelmas commented on 04_Datenbanken/databasecreate.py
> +            squad_sql = f"""DELETE FROM squads WHERE squadID = {squad_del_id} """
Wäre ebenfalls anfällig für eine SQL inection

2024-08-22 06:53 UTC, scibrahimelmas commented on 04_Datenbanken/databasecreate.py
> +            WHERE memberID = {member_del_id} """
Wäre ebenfalls anfällig für eine SQL inection

2024-08-22 06:54 UTC, scibrahimelmas commented on 04_Datenbanken/databasecreate.py
> +                f"""DELETE FROM memberPowers WHERE memberID = {member_del_id}"""
Wäre ebenfalls anfällig für eine SQL injection

2024-08-22 06:55 UTC, scibrahimelmas commented on 04_Datenbanken/databasecreate.py
> +            member_sql = f"""DELETE FROM members WHERE memberID = {member_del_id} """
Wäre ebenfalls anfällig für eine SQL injection

2024-08-22 06:55 UTC, scibrahimelmas commented on 04_Datenbanken/databasecreate.py
> +                squad_name_edit = f"""UPDATE squads SET squadName = "{new_squadname}"
Wäre ebenfalls anfällig für eine SQL injection

2024-08-22 06:55 UTC, scibrahimelmas commented on 04_Datenbanken/databasecreate.py
> +                WHERE squadID = "{squad_id}" """
Wäre ebenfalls anfällig für eine SQL injection

2024-08-22 06:59 UTC, scibrahimelmas requested changes
Siehe Kommentare

2024-08-22 13:26 UTC, scibrahimelmas approved these changes
Sieht gut aus

2024-08-23 05:45 UTC, Sc-Mae commented on 04_Datenbanken/databasecreate.py
> +            member_powers_sql = """DELETE FROM memberPowers WHERE memberID = %s"""
Das ganze ist anfällig für SQL-Injections. 
mit der eingabe von  "2 or 1=1"; kann man alle daten Löschen oder mit "; DROP DATABASE;"  kann die DB gelöscht werden. 
Lösung wäre ein Imput Validierung. Muss aber nicht implementiert werden.

2024-08-23 11:04 UTC, merged